name: weather-snap
version: git
summary: Command line weather tool.
description: |
Divya & Ajay

confinement: strict
base: core20

apps:
  wethr:
    command: bin/wethr

parts:
  wethr:
    plugin: npm
    npm-node-version: 14.16.1
    source: .
    source-version: git
